# Jekyll Defaults
title: Shuyi Tao
description: My personal site using Jekyll + blueface theme.
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://shuyirt.github.io"
github: https://github.com/shuyirt/shuyirt.github.io
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tagse
  url: /tags/
